version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - madhead
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - madhead
  - package-ecosystem: "npm"
    directory: "/mini-app"
    schedule:
      interval: "daily"
    assignees:
      - madhead
