stages:
  - test
  - report
  - build
  - package
  - prepare
  - deploy

check:
  stage: test
  image: openjdk:13
  script:
    - ./gradlew check jacocoTestReport
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    when: always
    expire_in: 1 day
    paths:
      - "**/build/reports"
      - "**/build/test-results"
      - "**/build/jacoco"
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"

test:db:
  stage: test
  image: openjdk:13
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: tyzenhaus
    POSTGRES_PASSWORD: tyzenhaus
    POSTGRES_PORT: 5432
    POSTGRES_DB: tyzenhaus
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  services:
    - postgres:12
  before_script:
    - yum install -y postgresql
  script:
    - ./gradlew :repository:postgresql:liquibaseUpdate
    - psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} <repository/postgresql/src/test/sql/seed.sql
    - ./gradlew dbTest jacocoDbTestReport
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    when: always
    expire_in: 1 day
    paths:
      - "**/build/reports"
      - "**/build/test-results"
      - "**/build/jacoco"
    reports:
      junit:
        - "**/build/test-results/dbTest/TEST-*.xml"

codecov:
  stage: report
  image: bash
  before_script:
    - apk add --no-cache curl
  script:
    - bash <(curl -s https://codecov.io/bash)

runner:heroku:dist:
  stage: build
  image: openjdk:13
  script:
    - ./gradlew clean :runner:heroku:installDist
  artifacts:
    paths:
      - runner/heroku/build/install/tyzenhaus
  only:
    - master

runner:heroku:docker:
  stage: package
  needs:
    - runner:heroku:dist
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build runner/heroku -t $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
  only:
    - master

runner:heroku:liquibase:
  stage: prepare
  needs:
    - test:db
  image: openjdk:13
  before_script:
    - yum install -y jq
  script:
    - >-
      curl
      https://api.heroku.com/apps/tyzenhaus/config-vars
      --header "Accept: application/vnd.heroku+json; version=3"
      --header "Authorization: Bearer $HEROKU_API_KEY"
      --output config-vars.json
    - export DATABASE_URL=$(jq -r '.DATABASE_URL' config-vars.json)
    - ./gradlew :repository:postgresql:liquibaseUpdate
  only:
    - master

runner:heroku:
  stage: deploy
  needs:
    - runner:heroku:liquibase
    - runner:heroku:docker
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u _                 -p $HEROKU_API_KEY       registry.heroku.com
  script:
    - docker pull $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/web:latest
    - docker tag $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA registry.heroku.com/tyzenhaus/web

    - docker push $CI_REGISTRY_IMAGE/web:latest

    - apk add --no-cache curl
    - docker push registry.heroku.com/tyzenhaus/web
    - docker inspect registry.heroku.com/tyzenhaus/web --format={{.Id}} > imageid
    - >-
      curl
      -X PATCH
      https://api.heroku.com/apps/tyzenhaus/formation
      --header "Content-Type: application/json"
      --header "Accept: application/vnd.heroku+json; version=3.docker-releases"
      --header "Authorization: Bearer $HEROKU_API_KEY"
      --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid)'" } ] }'
  only:
    - master
  environment:
    name: production-heroku
    url: https://tyzenhaus.herokuapp.com
