stages:
  - test
  - build
  - docker
  - deploy

check:
  stage: test
  image: openjdk:13
  script:
    - ./gradlew check
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    when: always
    expire_in: 1 day
    paths:
      - "**/build/reports"
      - "**/build/test-results"
      - "**/build/jacoco"
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"

db-test:
  stage: test
  image: openjdk:13
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: tyzenhaus
    POSTGRES_PASSWORD: tyzenhaus
    POSTGRES_PORT: 5432
    POSTGRES_DB: tyzenhaus
    POSTGRES_HOST_AUTH_METHOD: trust
  services:
    - postgres:12
  script:
    - echo "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" > .env
    - ./gradlew :repository:postgresql:update
    - ./gradlew dbTest

runner-heroku:
  stage: build
  image: openjdk:13
  script:
    - ./gradlew clean :runner:heroku:installDist
  artifacts:
    paths:
      - runner/heroku/build/install/tyzenhaus

runner-heroku-docker:
  stage: docker
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build runner/heroku -t $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA

runner-heroku-deploy-production:
  stage: deploy
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u _                 -p $HEROKU_API_KEY       registry.heroku.com
  script:
    - docker pull $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/web:latest
    - docker tag $CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA registry.heroku.com/tyzenhaus/web

    - docker push $CI_REGISTRY_IMAGE/web:latest

    - apk add --no-cache curl
    - docker push registry.heroku.com/tyzenhaus/web
    - docker inspect registry.heroku.com/tyzenhaus/web --format={{.Id}} > imageid
    - >-
      curl
      -X PATCH
      https://api.heroku.com/apps/tyzenhaus/formation
      --header "Content-Type: application/json"
      --header "Accept: application/vnd.heroku+json; version=3.docker-releases"
      --header "Authorization: Bearer $HEROKU_API_KEY"
      --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid)'" } ] }'
  only:
    - master
  environment:
    name: production-heroku
    url: https://tyzenhaus.herokuapp.com
