= Tyzenhaus Privacy Policy
:toc: macro
:sectnums:
:stylesheet: asciidoctor-tg.css
:linkcss:
:docinfo:
:nofooter:

[.normal]
This privacy policy for https://t.me/TyzenhausBot[@TyzenhausBot] (**"Tyzenhaus"**, **"we"**, **"us"**, or **"our"**), describes how and why we might collect, store, use, and/or share (**"process"**) your information when you use our services (**"Services"**), such as when you:

* Use our Telegram TPA (Third Party App) https://t.me/TyzenhausBot[@TyzenhausBot].
* Engage with us in other related ways, including any emails or direct messages.

**Questions or concerns?**
Reading this Privacy Notice will help you understand your privacy rights and choices.
If you do not agree with our policies and practices, please do not use our Services.
If you still have any questions or concerns, please contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

toc::[]

== Summary of key points

**What personal information do we process?**
When you visit, use, or navigate our Services, we may process personal information depending on how you interact with us and the Services, the choices you make, and the products and features you use.

**Do we process any sensitive personal information?**
We may process sensitive personal information when necessary.

**Do we collect any information from third parties?**
We do not collect any information from third parties.

**How do we process your information?**
We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law.
We may also process your information for other purposes.

**In what situations and with which parties do we share personal information?**
We may share information in specific situations and with specific third parties.

**What are your rights?**
You may stop using our Services or terminate your account at any time.

**How do you exercise your rights?**
Please contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].
We will consider and act upon any request in accordance with applicable data protection laws.

**Want to learn more about what we do with any information we collect?**
Review the Privacy Notice in full.

== What information do we collect?

=== Personal information you disclose to us

__**In Short:** We collect personal information that you provide to us.__

We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or otherwise when you contact us.

**Personal Information Provided by You.**
The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make, and the products and features you use.
The personal information we collect may include the following:

* Telegram user names
* Telegram user IDs

**Sensitive Information.**
When necessary, with your consent or as otherwise permitted by applicable law, we process the following categories of sensitive information:

* Financial data
** Shared expenses amounts, currencies, and descriptions
** Mutual user debts

All personal information that you provide to us must be true, complete, and accurate.

=== Information automatically collected

__**In Short:** Some information — such as your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our Services.__

We automatically collect certain information when you visit, use, or navigate the Services.
This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information.
This information is primarily needed to maintain the security and operation of our Services, and for our internal analytics and reporting purposes.

Like many businesses, we also use cookies and similar technologies.

The information we collect includes:

* __Log and Usage Data.__
Log and usage data is service-related, diagnostic, usage, and performance information our servers automatically collect when you access or use our Services and which we record in log files.
Depending on how you interact with us, this log data may include your IP address, device information, browser type, and settings and information about your activity in the Services (such as the date/time stamps associated with your usage, pages and files viewed, searches, and other actions you take such as which features you use), device event information (such as system activity, error reports (sometimes called "crash dumps"), and hardware settings).
* __Device Data.__
We collect device data such as information about your computer, phone, tablet, or other device you use to access the Services.
Depending on the device used, this device data may include information such as your IP address (or proxy server), device and application identification numbers, location, browser type, hardware model, Internet service provider and/or mobile carrier, operating system, and system configuration information.

== How do we process your information?

__**In Short:** We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law.
We may also process your information for other purposes with your consent.__

We process your personal information for a variety of reasons, depending on how you interact with our Services, including:

* **To facilitate authentication.**
We may process your information to keep your account in working order and your data secure.

* **To provide you our Services.**
We process your information when necessary to provide you our Services, such as to:
** Process and keep a history of your shared expenses
** Calculate and display mutual debts

== What legal bases do we rely on to process your information?

__**In Short:** We only process your personal information when we believe it is necessary, and we have a valid legal reason (i.e. legal basis) to do so under applicable law, like with your implied consent, to comply with laws, to provide you with services to enter into or fulfill our contractual obligations, to protect your rights, or to fulfill our legitimate business interests.__

[discrete]
=== If you are located in the EU or UK, this section applies to you.

The General Data Protection Regulation (GDPR) and UK GDPR require us to explain the valid legal bases we rely on in order to process your personal information.
As such, we may rely on the following legal bases to process your personal information:

* **Implied Consent.**
We process your information if you have given us permission to use your personal information for a specific purpose by using our Services (i.e. implied consent).
You can withdraw your consent at any time.

* **Legal Obligations.**
We may process your information where we believe it is necessary for compliance with our legal obligations, such as to cooperate with a law enforcement body or regulatory agency, exercise or defend our legal rights, or disclose your information as evidence in litigation in which we are involved.

* **Vital Interests.**
We may process your information where we believe it is necessary to protect your vital interests or the vital interests of a third party, such as situations involving potential threats to the safety of any person.

[discrete]
=== If you are located in Canada, this section applies to you.

We process your information if you have given us permission to use your personal information for a specific purpose by using our Services (i.e. implied consent).
You can withdraw your consent at any time.

In some exceptional cases, we may be legally permitted under applicable law to process your information without your consent, including, for example:

* If collection is clearly in the interests of an individual and consent cannot be obtained in a timely way
* For investigations and fraud detection and prevention
* For business transactions provided certain conditions are met
* If it is contained in a witness statement and the collection is necessary to assess, process, or settle an insurance claim
* For identifying injured, ill, or deceased persons and communicating with next of kin
* If we have reasonable grounds to believe an individual has been, is, or may be victim of financial abuse
* If it is reasonable to expect collection and use with consent would compromise the availability or the accuracy of the information and the collection is reasonable for purposes related to investigating a breach of an agreement or a contravention of the laws of Canada or a province
* If disclosure is required to comply with a subpoena, warrant, court order, or rules of the court relating to the production of records
* If it was produced by an individual in the course of their employment, business, or profession and the collection is consistent with the purposes for which the information was produced
* If the collection is solely for journalistic, artistic, or literary purposes
* If the information is publicly available and is specified by the regulations

== When and with whom do we share your personal information?

__**In Short:** We may share information in specific situations described in this section and/or with the following third parties.__

We may need to share your personal information in the following situations:

* **Business Transfers.**
We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.

== Do we use cookies and other tracking technologies?

__**In Short:** We may use cookies and other tracking technologies to collect and store your information.__

We may use cookies and similar tracking technologies (like web beacons and pixels) to gather information when you interact with our Services.
Some online tracking technologies help us maintain the security of our Services and your account, prevent crashes, fix bugs, save your preferences, and assist with basic site functions.

We also permit third parties and service providers (mainly Telegram) to use online tracking technologies on our Services for analytics and advertising, including to help manage and display advertisements, to tailor advertisements to your interests. The third parties and service providers use their technology to provide advertising about products and services tailored to your interests which may appear either on our Services or on other websites.

== How long do we keep your information?

__**In Short:** We keep your information for as long as necessary to fulfill the purposes outlined in this Privacy Notice unless otherwise required by law.__

We will only keep your personal information for as long as it is necessary for the purposes set out in this Privacy Notice, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements).
No purpose in this notice will require us keeping your personal information for longer than the period of time in which users have an account with us.

== Do we collect information from minors?

__**In Short:** We do not knowingly collect data from or market to minors.__

As a Telegram TPA (Third Party App), we rely and fully depend on its facilities in regard to users age.
Telegram does not provide any facilities to know the age of the users, thus, we treat all users equally in regard to their age.
Our Services do not knowingly provide any age-restricted content.
If you believe a minor has provided us with their personal information which should not have been provided, please contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

== What are your privacy rights?

__**In Short:** You may stop using our Services or terminate your account at any time.__

In some regions (like the EEA, UK, Switzerland, and Canada ), you have certain rights under applicable data protection laws.
These may include the right:

* to request access and obtain a copy of your personal information
* to request rectification or erasure
* to restrict the processing of your personal information
* if applicable, to data portability
* not to be subject to automated decision-making.

In certain circumstances, you may also have the right to object to the processing of your personal information.
You can make such a request by contacting us by contacting us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

We will consider and act upon any request in accordance with applicable data protection laws.

=== Withdrawing your consent

We process your information if you have given us permission to use your personal information for a specific purpose by using our Services (i.e. implied consent).

You have the right to withdraw your consent at any time.

You can withdraw your consent at any time by contacting us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

However, please note that this will not affect the lawfulness of the processing before its withdrawal nor, when applicable law allows, will it affect the processing of your personal information conducted in reliance on lawful processing grounds other than consent.

If you would at any time like to terminate your account, you can contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases.
However, we may retain some information in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our legal terms and/or comply with applicable legal requirements.

**Cookies and similar technologies:**
Most Web browsers are set to accept cookies by default.
Our Services, being a Telegram TPA (Third Party App), use your device's Web browser to interact with you and display information.
If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies.
If you choose to remove cookies or reject cookies, this could affect certain features or services of our Services.

If you have questions or comments about your privacy rights, you may contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

== Controls for do-not-track features

Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (**"DNT"**) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected.
At this stage, no uniform technology standard for recognizing and implementing DNT signals has been finalized.
As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online.
If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this Privacy Notice.

California law requires us to let you know how we respond to web browser DNT signals.
Because there currently is not an industry or legal standard for recognizing or honoring DNT signals, we do not respond to them at this time.

== Do United States residents have specific privacy rights?

__**In Short:** If you are a resident of some United States territories, states and/or other administrative divisions, including, but not limited to California, Colorado, Connecticut, Delaware, Florida, Indiana, Iowa, Kentucky, Montana, New Hampshire, New Jersey, Oregon, Tennessee, Texas, Utah, or Virginia, you may have the right to request access to and receive details about the personal information we maintain about you and how we have processed it, correct inaccuracies, get a copy of, or delete your personal information.
You may also have the right to withdraw your consent to our processing of your personal information.
These rights may be limited in some circumstances by applicable law.__

We do not currently provide any specific privacy rights to United States residents, and we treat all users equally in regard to their place of residence.
We believe that the level of protection provided by this Privacy Policy is sufficient for all users, regardless of their place of residence, and includes, but is not limited to, the aforementioned specific privacy rights applicable to United States residents.

If you have questions or comments about your privacy rights, you may contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

== Do other regions have specific privacy rights?

__**In Short:** If you are a resident of other regions, not mentioned in this Privacy Policy, you may have additional privacy rights.__

We do not currently provide any specific privacy rights based on users place of residence, and we treat all users equally in regard to their place of residence.
We believe that the level of protection provided by this Privacy Policy is sufficient for all users, regardless of their place of residence.

If you have questions or comments about your privacy rights, you may contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

== Do we make updates to this notice?

__**In Short:** Yes, we will update this notice as necessary to stay compliant with relevant laws.__

We may update this Privacy Notice from time to time.
The updated version will be indicated by an updated "Last updated" date at the top of this Privacy Notice.
If we make material changes to this Privacy Notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification.
We encourage you to review this Privacy Notice frequently to be informed of how we are protecting your information.

== How can you contact us about this notice?

If you have questions or comments about this notice, you may contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].

== How can you review, update, or delete the data we collect from you?

You have the right to request access to the personal information we collect from you, details about how we have processed it, correct inaccuracies, or delete your personal information.
You may also have the right to withdraw your consent to our processing of your personal information.
These rights may be limited in some circumstances by applicable law.
To request to review, update, or delete your personal information, please contact us via email at mailto:siarhei.krukau@gmail.com[siarhei.krukau@gmail.com] or via Telegram direct messages at https://t.me/m_a_d_h_e_a_d[@m_a_d_h_e_a_d].
