### Get me
GET https://api.telegram.org/bot{{telegram_token}}/getMe

### Get my commands
GET https://api.telegram.org/bot{{telegram_token}}/getMyCommands

### Set my commands
POST https://api.telegram.org/bot{{telegram_token}}/setMyCommands
Content-Type: application/json

{
    "commands": [
        {
            "command": "help",
            "description": "How to use the bot"
        },
        {
            "command": "lang",
            "description": "Change language"
        },
        {
            "command": "participate",
            "description": "Register yourself for expense tracking in this group"
        },
        {
            "command": "expense",
            "description": "Add a shared expense"
        },
        {
            "command": "debts",
            "description": "Show all the debts"
        },
        {
            "command": "history",
            "description": "Show transactions history"
        },
        {
            "command": "privacy",
            "description": "Show the Privacy Policy"
        }
    ]
}

### Set webhook
POST https://api.telegram.org/bot{{telegram_token}}/setWebhook
Content-Type: application/json

{
  "url": "https://{{ngrok}}/{{telegram_token}}"
}

### Validate initData
POST https://{{ngrok}}/app/api/auth/validation
Authorization: Bearer {{api_token}}

### Get group members
GET https://{{ngrok}}/app/api/group/members
Authorization: Bearer {{api_token}}

### Get group currencies
GET https://{{ngrok}}/app/api/group/currencies
Authorization: Bearer {{api_token}}

### Search for transactions
GET https://{{ngrok}}/app/api/group/transactions
Authorization: Bearer {{api_token}}
