### Get me
GET https://api.telegram.org/bot{{telegram_token}}/getMe HTTP/1.1

### Set webhook
POST https://api.telegram.org/bot{{telegram_token}}/setWebhook HTTP/1.1
Content-Type: application/json

{
  "url": "https://{{ngrok}}/{{telegram_token}}"
}

### Validate initData
POST https://{{ngrok}}/app/api/auth/validation
Authorization: Bearer {{api_token}}


### Get group members
GET https://{{ngrok}}/app/api/group/members
Authorization: Bearer {{api_token}}

### Get group currencies
GET https://{{ngrok}}/app/api/group/currencies
Authorization: Bearer {{api_token}}

### Search for transactions
GET https://{{ngrok}}/app/api/group/transactions
Authorization: Bearer {{api_token}}
