name: Default

on:
  push:
    branches-ignore:
      - master
      - crowdin

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit
    permissions:
      contents: read
      checks: write
      pull-requests: write
      security-events: write

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ./.github/actions/setup-jvm

      - run: ./gradlew :policies:privacy :launcher:fly:installDist

      - uses: ./.github/actions/setup-mini-app

      - run: yarn run build
        working-directory: mini-app
