name: Default

on:
  push:
    branches-ignore:
      - master

jobs:
  check-gradle-version:
    name: Check Gradle version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: madhead/check-gradle-version@v1
    continue-on-error: true

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check jacocoTestReport
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          retention-days: 1
          path: |
            **/build/reports
            **/build/test-results
            **/build/jacoco

  db-test:
    name: DB test
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: tyzenhaus
      POSTGRES_PASSWORD: tyzenhaus
      POSTGRES_PORT: 5432
      POSTGRES_DB: tyzenhaus
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :repository:postgresql:liquibaseUpdate
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
        env:
          DATABASE_URL: postgres://${{env.POSTGRES_USER}}:${{env.POSTGRES_PASSWORD}}@${{env.POSTGRES_HOST}}:${{env.POSTGRES_PORT}}/${{env.POSTGRES_DB}}
      - run: psql -h ${{env.POSTGRES_HOST}} -U ${{env.POSTGRES_USER}} -d ${{env.POSTGRES_DB}} <repository/postgresql/src/test/sql/seed.sql
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: dbTest jacocoDbTestReport
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
        env:
          DATABASE_URL: postgres://${{env.POSTGRES_USER}}:${{env.POSTGRES_PASSWORD}}@${{env.POSTGRES_HOST}}:${{env.POSTGRES_PORT}}/${{env.POSTGRES_DB}}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          retention-days: 1
          path: |
            **/build/reports
            **/build/test-results
            **/build/jacoco

  test-publish:
    name: Publish test results
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - db-test
    if: always()
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
      - uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/test-results/**/TEST-*.xml'

  codecov:
    name: CodeCov
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - db-test
    if: always()
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
      - run: bash <(curl -s https://codecov.io/bash)
