name: Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-heroku:
    name: Heroku deployment
    runs-on: ubuntu-latest
    environment:
      name: heroku
      url: https://tyzenhaus.herokuapp.com
    steps:
      - uses: actions/checkout@v3
      - uses: madhead/read-java-properties@latest
        id: version
        with:
          file: gradle.properties
          property: version
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :runner:heroku:installDist :runner:heroku:stats:installDist
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - uses: docker/build-push-action@v3
        with:
          context: runner/heroku
          push: true
          tags: >
            registry.heroku.com/tyzenhaus/web
      - run: docker push registry.heroku.com/tyzenhaus/web
      - run: docker inspect registry.heroku.com/tyzenhaus/web --format={{.Id}} > image_id
      - run: >-
          curl
          -X PATCH
          https://api.heroku.com/apps/tyzenhaus/formation
          --header "Content-Type: application/json"
          --header "Accept: application/vnd.heroku+json; version=3.docker-releases"
          --header "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}"
          --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat image_id)'" } ] }'
      - run: >-
          curl
          -X POST
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook
          --header "Content-Type: application/json"
          --data '{ "url": "https://tyzenhaus.herokuapp.com/${{ secrets.TELEGRAM_BOT_TOKEN }}" }'
